id = "just"
name = "Justfile"
description = "Justfile language support"
version = "0.2.0"
schema_version = 1
authors = [
  "Jack Taylor <j@jackt.io>",
  "Matt Robenolt <m@robenolt.com>",
]
repository = "https://github.com/jackTabsCode/zed-just"

[grammars.just]
repository = "https://github.com/terror/just-lsp"
rev = "37ee8d9e78c1ba7589d40c820f42a229f3ab487a"
path = "vendor/tree-sitter-just"

[language_servers.just-lsp]
name = "just-lsp"
languages = ["Just"]
